#!/bin/bash

# Script to transform the CL2QCD old options to new ones.
# It takes the input file to be updated as command line arguments, it
# creates a backup (where this script is used) and it overwrites
# the given file with the new names. The backup has as name the old
# file global path with / replaced by _.

declare -A OLD_NEW_OPTIONS_MAP
OLD_NEW_OPTIONS_MAP["approx_heatbath_file"]="rationalApproxFileHB"
OLD_NEW_OPTIONS_MAP["approx_lower"]="rationalApproxLowerBound"
OLD_NEW_OPTIONS_MAP["approx_md_file"]="rationalApproxFileMD"
OLD_NEW_OPTIONS_MAP["approx_metropolis_file"]="rationalApproxFileMetropolis"
OLD_NEW_OPTIONS_MAP["approx_upper"]="rationalApproxUpperBound"
OLD_NEW_OPTIONS_MAP["benchmarksteps"]="nBenchmarkIterations"
OLD_NEW_OPTIONS_MAP["beta"]="beta"
OLD_NEW_OPTIONS_MAP["cg_iteration_block_size"]="solverResiduumCheckEvery"
OLD_NEW_OPTIONS_MAP["cg_minimum_iteration_count"]="solverMinIterations"
OLD_NEW_OPTIONS_MAP["cg_use_async_copy"]="solverUseAsyncCopy"
OLD_NEW_OPTIONS_MAP["cgmax"]="solverMaxIterations"
OLD_NEW_OPTIONS_MAP["cgmax_mp"]="solverMaxIterationsMP"
OLD_NEW_OPTIONS_MAP["chem_pot_im"]="chemicalPotentialIm"
OLD_NEW_OPTIONS_MAP["chem_pot_re"]="chemicalPotentialRe"
OLD_NEW_OPTIONS_MAP["config_number_digits"]="nDigitsInConfCheckpoint"
OLD_NEW_OPTIONS_MAP["config_postfix"]="confPostfix"
OLD_NEW_OPTIONS_MAP["config_prefix"]="confPrefix"
OLD_NEW_OPTIONS_MAP["config_read_end"]="readUntilConfNumber"
OLD_NEW_OPTIONS_MAP["config_read_incr"]="readConfsEvery"
OLD_NEW_OPTIONS_MAP["config_read_start"]="readFromConfNumber"
OLD_NEW_OPTIONS_MAP["conservative"]="conservative"
OLD_NEW_OPTIONS_MAP["corr_dir"]="correlatorDirection"
OLD_NEW_OPTIONS_MAP["csw"]="csw"
OLD_NEW_OPTIONS_MAP["csw_mp"]="cswMP"
OLD_NEW_OPTIONS_MAP["device"]="deviceId"
OLD_NEW_OPTIONS_MAP["disable-ocl-compiler-opt"]="disableOclCompilerOptimization"
OLD_NEW_OPTIONS_MAP["enable_profiling"]="enableProfiling"
OLD_NEW_OPTIONS_MAP["ferm_obs_corr_postfix"]="fermObsCorrelatorsPostfix"
OLD_NEW_OPTIONS_MAP["ferm_obs_corr_prefix"]="fermObsCorrelatorsPrefix"
OLD_NEW_OPTIONS_MAP["ferm_obs_pbp_postfix"]="fermObsPbpPostfix"
OLD_NEW_OPTIONS_MAP["ferm_obs_pbp_prefix"]="fermObsPbpPrefix"
OLD_NEW_OPTIONS_MAP["ferm_obs_to_single_file"]="fermObsInSingleFile"
OLD_NEW_OPTIONS_MAP["fermact"]="fermionAction"
OLD_NEW_OPTIONS_MAP["fermact_mp"]="fermionActionMP"
OLD_NEW_OPTIONS_MAP["findminmax_iteration_block_size"]="findminmaxResiduumCheckEvery"
OLD_NEW_OPTIONS_MAP["findminmax_max"]="findminmaxMaxIterations"
OLD_NEW_OPTIONS_MAP["findminmax_prec"]="findminmaxPrecision"
OLD_NEW_OPTIONS_MAP["force_prec"]="solverForcePrecision"
OLD_NEW_OPTIONS_MAP["gauge_obs_postfix"]="gaugeObsPostfix"
OLD_NEW_OPTIONS_MAP["gauge_obs_prefix"]="gaugeObsPrefix"
OLD_NEW_OPTIONS_MAP["gauge_obs_to_single_file"]="gaugeObsInSingleFile"
OLD_NEW_OPTIONS_MAP["gaugeact"]="gaugeAction"
OLD_NEW_OPTIONS_MAP["heatbathsteps"]="nHeatbathSteps"
OLD_NEW_OPTIONS_MAP["help"]="help"
OLD_NEW_OPTIONS_MAP["hmc_obs_postfix"]="hmcObsPostfix"
OLD_NEW_OPTIONS_MAP["hmc_obs_prefix"]="hmcObsPrefix"
OLD_NEW_OPTIONS_MAP["hmc_obs_to_single_file"]="hmcObsToSingleFile"
OLD_NEW_OPTIONS_MAP["hmcsteps"]="nHmcSteps"
OLD_NEW_OPTIONS_MAP["host_seed"]="hostSeed"
OLD_NEW_OPTIONS_MAP["ignore_checksum_errors"]="ignoreChecksumErrors"
OLD_NEW_OPTIONS_MAP["initial_prng_state"]="initialPRNG"
OLD_NEW_OPTIONS_MAP["input-file"]="inputFile"
OLD_NEW_OPTIONS_MAP["integrationsteps0"]="integrationSteps0"
OLD_NEW_OPTIONS_MAP["integrationsteps1"]="integrationSteps1"
OLD_NEW_OPTIONS_MAP["integrationsteps2"]="integrationSteps2"
OLD_NEW_OPTIONS_MAP["integrator0"]="integrator0"
OLD_NEW_OPTIONS_MAP["integrator1"]="integrator1"
OLD_NEW_OPTIONS_MAP["integrator2"]="integrator2"
OLD_NEW_OPTIONS_MAP["iter_refresh"]="solverRestartEvery"
OLD_NEW_OPTIONS_MAP["iter_refresh_mp"]=""
OLD_NEW_OPTIONS_MAP["kappa"]="kappa"
OLD_NEW_OPTIONS_MAP["kappa_mp"]="kappaMP"
OLD_NEW_OPTIONS_MAP["lambda0"]="lambda0"
OLD_NEW_OPTIONS_MAP["lambda1"]="lambda1"
OLD_NEW_OPTIONS_MAP["lambda2"]="lambda2"
OLD_NEW_OPTIONS_MAP["log-level"]="logLevel"
OLD_NEW_OPTIONS_MAP["mass"]="mass"
OLD_NEW_OPTIONS_MAP["md_approx_ord"]="rationalApproxOrderHBAndMD"
OLD_NEW_OPTIONS_MAP["measure_correlators"]="measureCorrelators"
OLD_NEW_OPTIONS_MAP["measure_pbp"]="measurePbp"
OLD_NEW_OPTIONS_MAP["measure_rectangles"]="measureRectangles"
OLD_NEW_OPTIONS_MAP["measure_transportcoefficient_kappa"]="measureTransportCoefficientKappa"
OLD_NEW_OPTIONS_MAP["metro_approx_ord"]="rationalApproxOrderMetropolis"
OLD_NEW_OPTIONS_MAP["mu"]="mu"
OLD_NEW_OPTIONS_MAP["mu_mp"]="muMP"
OLD_NEW_OPTIONS_MAP["nspace"]="nSpace"
OLD_NEW_OPTIONS_MAP["ntime"]="nTime"
OLD_NEW_OPTIONS_MAP["num_dev"]="nDevices"
OLD_NEW_OPTIONS_MAP["num_pseudofermions"]="nPseudoFermions"
OLD_NEW_OPTIONS_MAP["num_sources"]="nSources"
OLD_NEW_OPTIONS_MAP["num_tastes"]="nTastes"
OLD_NEW_OPTIONS_MAP["num_tastes_decimal_digits"]="nTastesDecimalDigits"
OLD_NEW_OPTIONS_MAP["num_timescales"]="nTimeScales"
OLD_NEW_OPTIONS_MAP["overrelaxsteps"]="nOverrelaxationSteps"
OLD_NEW_OPTIONS_MAP["pbp_measurements"]="pbpMeasurements"
OLD_NEW_OPTIONS_MAP["pbp_version"]="pbpVersion"
OLD_NEW_OPTIONS_MAP["place_sources_on_host"]="placeSourcesOnHost"
OLD_NEW_OPTIONS_MAP["prec"]="precision"
OLD_NEW_OPTIONS_MAP["print_to_screen"]="printToScreen"
OLD_NEW_OPTIONS_MAP["prng_postfix"]="PRNGPostfix"
OLD_NEW_OPTIONS_MAP["prng_prefix"]="PRNGPrefix"
OLD_NEW_OPTIONS_MAP["profile_solver"]=""
OLD_NEW_OPTIONS_MAP["profiling_data_postfix"]="profilingDataPostfix"
OLD_NEW_OPTIONS_MAP["profiling_data_prefix"]="profilingDataPrefix"
OLD_NEW_OPTIONS_MAP["read_multiple_configs"]="readMultipleConfs"
OLD_NEW_OPTIONS_MAP["read_rational_approximations_from_file"]="readRationalApproxFromFile"
OLD_NEW_OPTIONS_MAP["rectanglesFilename"]="rectanglesFilename"
OLD_NEW_OPTIONS_MAP["reversibility_check"]=""
OLD_NEW_OPTIONS_MAP["rhmc_obs_postfix"]="rhmcObsPostfix"
OLD_NEW_OPTIONS_MAP["rhmc_obs_prefix"]="rhmcObsPrefix"
OLD_NEW_OPTIONS_MAP["rhmc_obs_to_single_file"]="rhmcObsToSingleFile"
OLD_NEW_OPTIONS_MAP["rhmcsteps"]="nRhmcSteps"
OLD_NEW_OPTIONS_MAP["rho"]="smearingFactor"
OLD_NEW_OPTIONS_MAP["rho_iter"]="nSmearingSteps"
OLD_NEW_OPTIONS_MAP["savefrequency"]="createCheckpointEvery"
OLD_NEW_OPTIONS_MAP["savepointfrequency"]="overwriteTemporaryCheckpointEvery"
OLD_NEW_OPTIONS_MAP["solver"]="solver"
OLD_NEW_OPTIONS_MAP["solver_mp"]="solverMP"
OLD_NEW_OPTIONS_MAP["solver_prec"]="solverPrecision"
OLD_NEW_OPTIONS_MAP["source_t"]="sourceT"
OLD_NEW_OPTIONS_MAP["source_x"]="sourceX"
OLD_NEW_OPTIONS_MAP["source_y"]="sourceY"
OLD_NEW_OPTIONS_MAP["source_z"]="sourceZ"
OLD_NEW_OPTIONS_MAP["sourcecontent"]="sourceContent"
OLD_NEW_OPTIONS_MAP["sourcefile"]="initialConf"
OLD_NEW_OPTIONS_MAP["sourcetype"]="sourceType"
OLD_NEW_OPTIONS_MAP["split_cpu"]="splitCPU"
OLD_NEW_OPTIONS_MAP["startcondition"]="startCondition"
OLD_NEW_OPTIONS_MAP["tau"]="tau"
OLD_NEW_OPTIONS_MAP["thermalization"]="nThermalizationSteps"
OLD_NEW_OPTIONS_MAP["theta_fermion_spatial"]="thetaFermionSpatial"
OLD_NEW_OPTIONS_MAP["theta_fermion_temporal"]="thetaFermionTemporal"
OLD_NEW_OPTIONS_MAP["transportcoefficientKappaFilename"]="transportCoefficientKappaFilename"
OLD_NEW_OPTIONS_MAP["use_aniso"]="useAnisotropy"
OLD_NEW_OPTIONS_MAP["use_chem_pot_im"]="useChemicalPotentialIm"
OLD_NEW_OPTIONS_MAP["use_chem_pot_re"]="useChemicalPotentialRe"
OLD_NEW_OPTIONS_MAP["use_cpu"]="useCPU"
OLD_NEW_OPTIONS_MAP["use_eo"]="useEO"
OLD_NEW_OPTIONS_MAP["use_gauge_only"]="useGaugeOnly"
OLD_NEW_OPTIONS_MAP["use_gpu"]="useGPU"
OLD_NEW_OPTIONS_MAP["use_merge_kernels_fermion"]="useKernelMergingFermionMatrix"
OLD_NEW_OPTIONS_MAP["use_merge_kernels_spinor"]="useKernelMergingSpinor"
OLD_NEW_OPTIONS_MAP["use_mp"]="useMP"
OLD_NEW_OPTIONS_MAP["use_rec12"]="useReconstruct12"
OLD_NEW_OPTIONS_MAP["use_same_rnd_numbers"]="useSameRandomNumbers"
OLD_NEW_OPTIONS_MAP["use_smearing"]="useSmearing"
OLD_NEW_OPTIONS_MAP["writefrequency"]="onlineMeasureEvery"
OLD_NEW_OPTIONS_MAP["xi"]="xi"


function PrintError(){
    printf "\e[38;5;9m \e[1m\e[4mERROR\e[24m:\e[21m %s\e[0m\n\n" "$1"
}

while [ $# -gt 0 ]; do
    if [ -f "$1" ]; then
        fileGlobalPath="$(cd "$(dirname "$1")"; pwd)/$(basename "$1")"
        backupName="${fileGlobalPath////_}"; backupName=${backupName:1}
        if [ -f "$backupName" ]; then
            PrintError "Backup file \"$backupName\" alredy existing! Skipping it."
        else
            cp "$1" "$backupName" || exit -2
            # Here assume there are no spaces in old and new options!
            for oldOption in ${!OLD_NEW_OPTIONS_MAP[@]}; do
                newOption=${OLD_NEW_OPTIONS_MAP[${oldOption}]}
                sed -i 's/'${oldOption}'/'${newOption}'/g' "$1"
            done
        fi
    else
        PrintError "File \"$1\" not found! Skipping it."
    fi
    shift
done

