(* ::Package:: *)

(* ::Input:: *)
(*(*--------------------------------------------------------------------------------------------------------------------------------------*)*)
(*(* TEMPLATE FOR QUANTITATIVE COLLAPSE PLOT: USE THIS FILE TO GET A ROUGH IDEA OF THE PARAMETER RANGE WHERE TO DO THE MINIMIZATION *)*)
(*(*--------------------------------------------------------------------------------------------------------------------------------------*)*)
(**)
(*(* Before the first use, you need to complete some of the commands, providing the asked information.  *)*)
(*(* Search in this file the string ">>>>>" after which a short description of what is needed is given! *)*)
(**)
(*(*-------------------------------------------------------------------------------------------------------------------------------------------------------------------*)*)
(*Needs["ErrorBarPlots`"]*)
(*SetOptions[$FrontEndSession,PrintPrecision->10]*)
(*AppendTo[$Path,">>>>> GLOBALPATH TO FOLDER CONTAINING THE PACKAGE, IT SHOULD BE IN THE SAME FOLDER WHERE YOU FOUND THIS FILE"];*)
(*If[FindFile["AnalyticCollapse`"]===$Failed,Print["Package \"AnalyticCollapse\" could not be loaded! Aborting..."];Abort[],Get["AnalyticCollapse`"]]*)
(*(*-------------------------------------------------------------------------------------------------------------------------------------------------------------------*)*)
(*(*The datafile must be in the format: {{Beta, Kurtosis}}*)*)
(*NamesOfFiles={*)
(*">>>>> LIST OF FILES (GLOBALPATHS) THAT CONTAIN THE DATA TO BE COLLPASED. USUALLY, THEY ARE PRODUCED FROM THE BASH HANDLER",*)
(*">>>>> USING IT WITH THE -p OPTION AND GIVING TO IT THE REWEIGHTING OUTPUT FILES.",*)
(*">>>>> REMEMBER THAT THE LAST ELEMENT OF A MATHEMATICA LIST SHOULD NOT BE FOLLOWED BY A COMMA, SO REMOVE IT IF YOU",*)
(*">>>>> HAVE LESS FILES THAN 4, LIKE IN THIS EXAMPLE."*)
(*};*)
(*(*The estimator datafile must be in the format: {{EstimatorNumber, Beta, Kurtosis}}*)*)
(*NamesOfFilesWithEstimators=StringInsert[#,"_estimators",-5]&/@NamesOfFiles;*)
(*(*-------------------------------------------------------------------------------------------------------------------------------------------------------------------*)*)
(*(*Checks on the existence of the files*)*)
(*If[!FileExistsQ[#],Print[StringForm["File \"``\" not found! Aborting...",#]];Abort[]]&/@Join[NamesOfFiles];*)
(*(*Check on the name of the files:they must contain "ns" with at least one digit afterwards*)*)
(*If[Length[StringCases[#,RegularExpression["ns[[:digit:]]+"]]]!=1,*)
(*Print[StringForm["File \"``\" does not contain one and only one occurence of \"ns[[::digit]]+\"! Aborting...",#]];Abort[]*)
(*]&/@StringReplace[NamesOfFiles,RegularExpression[".*/"]->""];*)
(*(*-------------------------------------------------------------------------------------------------------------------------------------------------------------------*)*)
(*(*Import data*)*)
(*Volume[filename_]:=*)
(*Module[{basename},*)
(*basename=StringReplace[filename,RegularExpression[".*/"]->""];*)
(*ToExpression[StringCases[StringCases[basename,RegularExpression["ns[[:digit:]]+"]],RegularExpression["[[:digit:]]+"]][[1,1]]]*)
(*]*)
(*AllDataInBeta={Import[#],Volume[#]}&/@NamesOfFiles;*)
(*(*-------------------------------------------------------------------------------------------------------------------------------------------------------------------*)*)
(*(*Make rough scan to understand where to run accurate scan*)*)
(*ContinuousDiscretization=(*>>>>> True OR False DEPENDING WHICH MINIMIZATION IS DESIRED*);*)
(*betaMin=(*>>>>>*); betaMax=(*>>>>>*); betaRes=(*>>>>>*);*)
(*nuMin = (*>>>>>*); nuMax = (*>>>>>*); nuRes = (*>>>>>*); dxFactor=(*>>>>>*);*)
(*If[ContinuousDiscretization,*)
(*Print[MinimizeNumericallyQualityOfCollapse[AllDataInBeta,betaMin,betaMax,nuMin,nuMax,dxFactor]];,*)
(*scanResult=AbsoluteTiming[MakeScanInBetaCAndNu[AllDataInBeta,betaMin,betaMax,betaRes,nuMin,nuMax,nuRes,dxFactor]];*)
(*Print[scanResult[[1]]]; Print[FindMinimumVarianceAndPrintCollapseParametersFromDiscreteScan[scanResult[[2]]]];*)
(*MakePlotOfScanSeparatingBlocksOfBetas[scanResult[[2]]]*)
(*]*)
(*Clear[ContinuousDiscretization,betaMin,betaMax,betaRes,nuMin,nuMax,nuRes,dxFactor];*)
(*(*-------------------------------------------------------------------------------------------------------------------------------------------------------------------*)*)
(**)
(**)
